add report flag for printing key presses to console
DaveJarvis/kmcaster pull request #25
Opened 2023-01-06 08:00 UTC by maxandersen

making it easier for users to help report misreported keys.

chose '--report/-r' as both 'd' and 'v' flags already taken.

2023-01-06 20:22 UTC, DaveJarvis requested changes
Thank you, Max, this was entirely unexpected and is an incredibly useful idea. Last year, I jotted down some ideas on logging that I believe are relevant:

https://dave.autonoma.ca/blog/2022/01/08/logging-code-smell/

In effect, logging shouldn't be relegated to multiple print statements, but rather centralized via events to a single location in the source base. If you're willing to make some changes, here's what I'd like to see from a high-level:

* Change the `-d`/`--dimension` to free up the letter (can't use `-h` because that's _help_). How about `-p`/`--proportions` to change the height?
* Introduce `-d`/`--debug`, which is conventional.
* Add a `DebugListener` that listens for key events (i.e., implements `NativeKeyListener`).
* Update `KmCaster`'s `initListener` method with: `initDebugListener()`.

Getting into the weeds a little, the `initDebugListener()` method could look something like:

``` java
  private void initDebugListener() {
    if( isDebugEnabled() ) {
      final DebugListener debugListener = new DebugListener();
      addNativeKeyListener( debugListner );
    }
  }
```

That way the `KeyboardListener`, whose analog is the `MouseListener`, is only responsible for one thing: updating the user interface when the keyboard status changes. It is not responsible for logging or debugging (because those are cross-cutting concerns). All the debugging and printing logic can then be isolated to `DebugListener`.

Here's an example implementation of `DebugListener`:

``` java
package com.whitemagicsoftware.kmcaster.listeners;

import com.github.kwhat.jnativehook.keyboard.NativeKeyEvent;
import com.github.kwhat.jnativehook.keyboard.NativeKeyListener;

public final class DebugListener implements NativeKeyListener {

  private String mPrevious;

  @Override
  public void nativeKeyTyped( final NativeKeyEvent event ) {
    log( event );
  }

  @Override
  public void nativeKeyPressed( final NativeKeyEvent event ) {
    log( event );
  }

  @Override
  public void nativeKeyReleased( final NativeKeyEvent event ) {
    log( event );
  }

  private void log( final NativeKeyEvent event ) {
    assert event != null;
    
    final var param = event.paramString();
    
    if( !param.equals( mPrevious ) ) {
      mPrevious = param;
      System.out.println( param );
    }
  }
}
```

Style-wise, please note the following

* Try to adhere to the "ambient" style of existing source files with respect to formatting/spaces/whitespace/indentation. (I don't have an external config file set up, sorry!)
* Instance variables are declared at the top of the class, as per typical Java conventions.
* Instance variables are prefixed with `m` (instead of `this.`), static variables with `s`, and constants in UPPER_SNAKE_CASE.

Note how this example implementation:

* Avoids the magic number `-1`.
* Has a single print statement, rather than two, thereby adhering to the DRY principle.
* Filters out held keys and multiple consecutive key-presses using the same logic.
* Does not need to check whether debugging is enabled at every key press.
* Avoids changing the logic for `KeyboardListener`.
* Applies the [Single-Responsibility Principle](https://en.wikipedia.org/wiki/Single-responsibility_principle).

2023-01-08 21:37 UTC, DaveJarvis commented
@maxandersen -- I've run into a Windows 10 issue with function keys not showing. I'll fix this, so I'm closing the PR.

2023-01-08 21:37 UTC, closed without merging

2023-01-09 09:10 UTC, maxandersen commented
so you'll add the debug listener? great.

2023-01-09 16:51 UTC, DaveJarvis commented
https://github.com/DaveJarvis/kmcaster/blob/main/src/main/java/com/whitemagicsoftware/kmcaster/listeners/DebugListener.java